version: 0.1

phases:
  build:
    commands:
      - ls
      - npm run build
  post_build:
    commands:
      - mv 404.html build
      - mv glide-spot-logo-coloured.svg build
      - mkdir ./build/material-dashboard-react
      - ls build
      - mv ./build/static ./build/material-dashboard-react
      - aws s3 sync ./build s3://material-ui/
      # - aws cloudformation package --template-file app-sam.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file app-output_sam.yaml

